#!/usr/bin/perl
use strict;

###############################################
# vtop for slicestat by KyoungSoo Park
###############################################

open THIS_PIPE, "/usr/sbin/vtop bn1 |";
while(<THIS_PIPE>) {
    print;
}
close THIS_PIPE;
