#!/usr/bin/python

import sys
import pwd
import re
import socket
import struct
import os
import string

vsys_config_dir = "/etc/planetlab/vsys-attributes"

if len(sys.argv) != 2: sys.exit(1)

slicename=sys.argv[1]
sliceid = pwd.getpwnam(slicename).pw_uid
dpname = "dp-%d"%sliceid

### Read args from stdin
arglines = map(string.strip, sys.stdin.readlines())
if len(arglines) != 1: sys.exit(1)
of_server = arglines[0]

if re.match(r'^(tcp|udp):[\d\.]+$', vif) is None: exit(1)

print "Requesting creation of data path %s."%dpname
os.system("ovs-openflowd dp0 tcp:192.168.1.2")
