#!/usr/bin/perl

$|=1;
$slice=$ARGV[0];
$slice_ip=`cat /etc/vservers/$slice/interfaces/0/ip`;
$src_port = <STDIN>;
$dst_port = <STDIN>;

chomp($slice_ip);
chomp($src_port);
chomp($dst_port);

die ("Src and dst ports need to be numbers") if (($src_port=~/[^0-9]/) || ($src_port=~/[^0-9]/));

$IPTABLES_CMD="/sbin/iptables -t nat -A PREROUTING -m tcp -p tcp -d $slice_ip --dport $src_port -j DNAT --to-destination $slice_ip:$dst_port";
print "Invoking port forwarding command: $IPTABLES_CMD\n";
system($IPTABLES_CMD);
print "Done.\n";
