#!/bin/sh
# Mount the planetflow directory in a slice

#mount --bind /usr/local/fprobe /vservers/$1/pf
# changed from request of Faiyaz
DEST="/vservers/$1/pf"
mount | grep "on $DEST type" > /dev/null
if [ $? -eq 1 ]; then
    mount --bind /var/local/fprobe -o ro $DEST
fi
