#!/usr/bin/perl

use strict;

my $slicename=$ARGV[0];
my $slice_dir="/vservers/$slicename/";
my $localpath = <STDIN>;

chomp($localpath);

$localpath=$slice_dir.$localpath;

my $pathtest;

$pathtest='';
while ($localpath=~/(\/?[\w\d\-_]+\/?)/g) {
    $pathtest=$pathtest.$1;
}

if ($pathtest ne $localpath) {
    die "$localpath is not a safe path";
}

my $mntcmd="/bin/umount $localpath";
system($mntcmd);

if ($?) {
    print "Mount failed: $?";
}
